services:
  db:
    container_name: postgres
    image: postgres:16.8-alpine3.20
    ports: 
      - 5432:5432
    restart: always
    volumes: 
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME