services:
  db:
    container_name: postgres
    image: postgres:14.17-alpine3.21
    ports: 
      - 5432:5432
    restart: always
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data:
    external: false